name: Build dylib

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up
        run: echo "Building libexploit.dylib"

      - name: Build shared library
        run: |
          gcc -shared -fPIC -o libexploit.dylib exploit.c
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dylib
          path: libexploit.dylib
